### PR TITLE
Add use-package-defaults

### PR DESCRIPTION
**Pull request by raxod502**
Previously, the :config, :ensure, and :pin keywords had default
values (dependent on the values of the use-package-always-ensure and
use-package-always-pin). This change allows the user to customize the
default values used for those keywords, and add default values for
their own keywords in a non-hacky way.

This functionality would be useful for (as an example) the
quelpa-use-package package, which needs to use an advice to override
the functionality of :ensure. The same problem prevents adding a
use-package-always-quelpa variable in any reasonable way, without a
way to customize the default values of keywords.

### CODE REVIEW

**Comment by raxod502** [comment]
Rebased to fix conflicts.

**Comment by raxod502** [comment]
Any update on this?

**Comment by jwiegley** [comment]
@raxod502 Have you submitted a copyright assignment form to the FSF for your work on Emacs?  That's all I would need before merging, since this code is intended to be shipped with Emacs in the near future.  And thank you very much for the change and the idea!

**Comment by raxod502** [comment]
I have emailed assign@gnu.org.

**Comment by jwiegley** [comment]
Great!  Let me know once they've confirmed, and I'll merge.

**Comment by raxod502** [comment]
@jwiegley They have confirmed my copyright assignment. I am disappointed there seems to be no straightforward way for me to demonstrate that, but let me know if there is anything I can do.

**Comment by jwiegley** [comment]
@raxod502 Hi, as a GNU project maintainer I can access the master list directly, and I see your assignment on file. Thank you!

**Comment by jwiegley** [comment]
@raxod502 I've received reports in two other bugs now that some keywords have suddenly become ordering dependent: i.e., unless A is used before B, it does not take effect.  They claim it's due to this change, so I may need to revert it for the time being until we figure out what's wrong.

**Comment by jwiegley** [comment]
Reverted the merge in fe736725dee694e25a944dd6368b5774fa347867.

**Comment by jwiegley** [comment]
Problem was seen in #429 and #428.

**Comment by raxod502** [comment]
That's very concerning! I didn't understand why the code was set up the way it was, so I tried to replicate the exact logic. Clearly I failed, let me take a look at it again.

**Pull request merged**
