### PR TITLE
Enable lexical binding

### LINKED ISSUE #648: Use lexical-binding
Why isn't use-package using lexical-binding for all files?

I volunteer to fix this if desired.

### PR DESCRIPTION
**Pull request by jabranham**
This supercedes #617 and closes #648

### CODE REVIEW

**Comment by jabranham** [comment]
Looks like the test for `use-package-normalize-function` fails. I don't have time now, but will take a look later.

**Comment by npostavs** [comment]
I think it's an error in the test, it looks to be making the exact same mistake as described in [Emacs Lisp Lambda Expressions Are Not Self-Evaluating](https://nullprogram.com/blog/2018/02/22/)

**Comment by DamienCassou** [comment]
I've switched to your branch and will report if I find problems.

**Comment by DamienCassou** [comment]
I've used this branch for 2 weeks now without problems. Can it be merged?

**Comment by jwiegley** [comment]
I need to try it with my configuration first, since that failed spectacularly the last time this was tried. I'll let you know soon.

**Comment by jabranham** [comment]
@jwiegley I did some digging last time and think I figure out what you need: https://github.com/jwiegley/use-package/pull/617#issuecomment-361023166

**Comment by jwiegley** [comment]
I'm so glad you reminded me. Yes, that very likely is the problem.

I don't really use `:load-path` much anymore, since I configure Emacs using Nix these days and it manages the load path for me. So this is probably the right time to give this another try.

**Comment by DamienCassou** [comment]
What is the status of this PR? I would like to get that in. It has been working for me for a month.

**Comment by jabranham** [comment]
I'm not sure there's much to do on my end. I've been using it for a
while without any problems. Someone let me know if I'm mistaken and I
can take a look at whatever needs to be changed.

**Comment by jwiegley** [comment]
I just need to give a try on my own config, it's on my list. Also, there's a test failing.

**Comment by DamienCassou** [comment]
@jabranham could you please update your branch?

**Comment by jabranham** [comment]
Rebased off master, thanks for the nudge @DamienCassou

**Comment by jabranham** [comment]
@npostavs do you have a way to fix that test? I took a look at the blog post you shared and have tried various combinations of quoting without success so far.

**Comment by npostavs** [comment]
I believe the quoting should be like this:
```elisp
(equal (use-package-normalize-function '(lambda () ...)) '(lambda () ...))
(equal (use-package-normalize-function ''(lambda () ...)) '(lambda () ...))
(equal (use-package-normalize-function '#'(lambda () ...)) '(lambda () ...))
```
But that still fails, I think because https://github.com/jwiegley/use-package/commit/9ce9c048a14967b4764872107c0ae9260febc44b#diff-8ef140df8b4408418fab781244480094L776 did not rewrite `use-package-normalize-function` correctly (the expressions above do all give `t` with the `pcase` version).

**Comment by jabranham** [comment]
@npostavs They don't give `t` for me even with the pcase version. For example:

```
(equal (use-package-normalize-function '(lambda () ...)) (lambda () ...))
```

becomes

```
(equal (lambda nil \.\.\.) (closure (t) nil \.\.\.))
```

which evaluates to `nil`. I get the same thing with the current non-pcase version too.

**Comment by npostavs** [comment]
> For example:
> 
>     (equal (use-package-normalize-function '(lambda () ...)) (lambda () ...))

You need to quote the right hand side `lambda` too.

**Comment by jabranham** [comment]
D'oh! Of course.

**Comment by jabranham** [comment]
So here's the reason for the test failing:

Doing
```emacs-lisp
(use-package-normalize-function ''(lambda () ...))
```

eventually tries to evaluate:

```emacs-lisp
(memq '(quote function) (car ''(lambda () ...))
```

which is a type error. The same thing happens if you try `(use-package-normalize-function '#'(lambda ...)`

**Comment by jabranham** [comment]
Is it enough to just directly check if we're dealing with a quoted function?

```diff
From 894a3fe48c9251cf2103aada228f7b309f555a5a Mon Sep 17 00:00:00 2001
From: Alex Branham <branham@utexas.edu>
Date: Tue, 22 May 2018 12:10:21 -0500
Subject: [PATCH] Check for functions in use-package-normalize-function

---
 use-package-core.el | 2 ++
 1 file changed, 2 insertions(+)

diff --git a/use-package-core.el b/use-package-core.el
index 9f7828f..27232c8 100644
--- a/use-package-core.el
+++ b/use-package-core.el
@@ -919,6 +919,8 @@ If RECURSED is non-nil, recurse into sublists."
         ((and (consp v)
               (eq 'lambda (car v)))
          v)
+        ((functionp (nth 1 v))
+         (nth 1 v))
         ((and (listp v)
               (memq '(quote function) (car v))
               (eq 'lambda (car (cadr v))))
-- 
2.17.0

```

**Comment by npostavs** [comment]
Actually, should that `(memq '(quote function) (car v))` be `(memq (car v) '(quote function))`?

**Comment by jabranham** [comment]
Oh, right. And it's there, just a few lines up!

**Comment by jabranham** [comment]
Rebased off master

**Comment by jwiegley** [comment]
This is working great for me now, thanks. I just had to fix a bug in my `load-path-handler-override`, which I'm surprised was never causing an issue before.

**Pull request merged**
