### PR TITLE
Pass more information to :ensure function

### PR DESCRIPTION
**Pull request by raxod502**
This pull request supersedes https://github.com/jwiegley/use-package/pull/552.

@jwiegley Can you confirm that this seems reasonable? If so, I will go ahead and update the test suite (which is currently failing).

### CODE REVIEW

**Comment by jwiegley** [comment]
I don't quite understand what this change aims to do. At the very least, you need `use-package-normalize/:ensure`, otherwise it's an error for the keyword's normalizer to be missing. Should this function just be calling the new one you've defined?

**Comment by raxod502** [comment]
@jwiegley What this change aims to do is have the normalization take place _inside `use-package-ensure-elpa`_, rather than in the normalizer. This is because different package managers will have different ways of interpreting the forms passed to `:ensure`. I've updated the branch to re-add a normalizer that does nothing to its `args` list.

**Comment by jwiegley** [comment]
Yes, but you deleted the normalizer, which will result in an error.

**Comment by jwiegley** [comment]
I wonder if we're going about this the wrong way. Perhaps other package managers should just use a different keyword rather than `:ensure`?

**Comment by raxod502** [comment]
@jwiegley That's fair—would it make more sense for the keyword to be called `:package`, then?

**Comment by jwiegley** [comment]
I was thinking more `:straight`, for example. The only reason to make `:ensure` the front-end for any package manager, would be to allow transparent switching from one package manager to another, but I'm not convinced this is a use case we should optimize for -- since it makes the code just that much harder to test. If instead each package manager adds their own keyword to `use-package-keywords`, then they can do whatever they want, and advertise whatever sub-keywords they need to their users.

**Comment by raxod502** [comment]
Yeah, I agree—but what I meant is that `straight.el` would have the keyword `:straight`, and `package.el` would have the keyword `:package`.

**Comment by raxod502** [comment]
For backward compatibility, `:ensure` could just be an alias for `:package`. And then you get the "transparently switch between package managers" use case for free, because the user can just redefine `:ensure` as an alias for `:straight` instead, if they want.

**Comment by jwiegley** [comment]
I suppose, if you're ok with accepting the same arguments that `:ensure` does.

**Comment by raxod502** [comment]
Well, if we did as I propose, then there wouldn't be any concept of "the same arguments that `:ensure` does". But, yes, the idea of redefining `:ensure` to be an alias to `:straight` instead of `:package` would only work for those cases where `:straight` takes arguments of the same form as `:package`. That's why it wouldn't really be a supported use case. I just thought it would be a nice, elegant way to preserve backwards compatibility.

Besides, `:ensure` is kind of a weird name for a keyword. I feel like `:package` makes more sense, in addition to implicitly introducing a naming schema for other package managers.

There is the concern of deferred installation, which might be most elegant to implement in a package-manager-agnostic way. I have no objection, however, to making each package manager provide its own support for this, and it could also be argued that different package managers will probably be different enough that this would make more sense. (And of course *I* only care about deferred installation support for `straight.el` 😄)

**Comment by raxod502** [comment]
In any case, I don't need any changes here to make `straight.el` work. What _would_ be nice is, as you mentioned in https://github.com/jwiegley/use-package/pull/552#issuecomment-349387607:

> `use-package-defaults` should probably be changed to use *pre-normalization* values, although right now it's using *post-normalization* values.

At the moment I kind of have to hack around in order to get my `:straight` keyword to default to the package name.

**Pull request closed without merging**
