### PR TITLE
Add support for key-chord keyword `:chords`

### PR DESCRIPTION
**Pull request by waymondo**

### CODE REVIEW

**Comment by jwiegley** [comment]
@waymondo Could we implement this as an addon package that one would load after `use-package`, for example with `(require 'up-chords)`.  I'm wary of adding new core functionality that I wouldn't use (and hence couldn't maintain or determine the fitness of).  The whole promise of use-package 2.0 is that you should be able to offer an extension like this without having to add it to core use-package itself.

**Comment by waymondo** [comment]
Ok that would work for me. I was pleased with how easy of an addition it was, so I tried to slip it into the main project. I will create an extension package for it then.

**Comment by kaushalmodi** [comment]
@waymondo Can you post your `:chords` implementation or a link to it over here for reference? Thanks.

**Comment by waymondo** [comment]
just posted it to GH (https://github.com/waymondo/use-package-chords) and submitted it to MELPA, waiting for approval.

**Comment by kaushalmodi** [comment]
@waymondo :+1:

**Comment by kaushalmodi** [comment]
Tagging @jordonbiondo as he might be interested in this [`use-package-chords`][1] package too.

[1]: https://github.com/waymondo/use-package-chords

**Comment by jordonbiondo** [comment]
Awesome, I have been meaning to do this for myself for a long time, nice job getting it out. Now I can finally start using 2.0!

**Comment by waymondo** [comment]
@jordonbiondo I was actually inspired by seeing the `:chords` keyword in your `.emacs.d`, and the 2.0 refactoring made it quite easy to port it. So props back at you!

**Comment by jwiegley** [comment]
Nice and clean addon, I like it.  This will be a good example for showing others how to add more custom keywords.

**Pull request closed without merging**
