### PR TITLE
new use-package logo

### LINKED ISSUE #577: Icon/logo for use-package?
Hello,

We'll need a logo for the use-package site.

Right now, the [site][1] is using the Org mode logo as placeholder.

image

[1]: https://jwiegley.github.io/use-package/

### PR DESCRIPTION
**Pull request by hubisan**
This commit closes #577

1. Added new use-package logo files

- Overwritten existing .png files with new .png files in static folder
- Overwritten existing .ico file with new .ico file that has multiple
dimensions (16x16, 32x32, 48x48)
- Added img folder
- Added svg-file that will be used as main logo to img folder
- Added the logo source files to /img/logo-raw folder if any changes are needed
in the future

2. Changes to config.toml

- Added param favicon to force load the new favicon (v=1) and not a cached one
- Changed logo path to img/use-package-logo-96x96-v1.svg (using vector instead of png)

3. Tested locally (Desktop Ubuntu Firefox & Chrome)

Everything seems to be working:

use-package-logo-test

### CODE REVIEW

**Comment by jwiegley** [comment]
Are the `.ai` files Adobe Illustrator source files?  I'm pretty sure we can include the .SVG files, if you've signed your papers with the FSF, but I doubt they'd accept source files that can only be opened by proprietary software. Is that the case?

**Comment by nickmccurdy** [comment]
It seems like there's one SVG export of the 96x96 AI files, it would be nice to replace them with an SVG for each.

**Comment by hubisan** [comment]
I can replace the .ai (Adobe Illustrator) with .svg (some features used in .ai will probably not be editable anymore).

Do I have to assign copyright to the FSF for this change?

**Comment by jwiegley** [comment]
Nice, once they accept let me know and we'll merge this.

**Comment by hubisan** [comment]
@jwiegley Just received the completed assignment (GNU Emacs) from FSF.

**Pull request merged**
