### PR TITLE
typo, should be a vector, not a bytecode object

### PR DESCRIPTION
**Pull request by nahuel**
Solves https://github.com/jwiegley/use-package/issues/842

### CODE REVIEW

**Comment by arichiardi** [comment]
It looks good to me, thanks for the quick fix - kind of scared this morning when I woke up that I broke something :smile:

**Comment by jwiegley** [comment]
Thank you!

**Comment by Silex** [comment]
So this was broken since two (!) years :scream:

 https://github.com/jwiegley/use-package/blame/0ba3071cda77957822bfe3e58009375f395777f4/use-package-core.el#L1033

Original commit: https://github.com/jwiegley/use-package/commit/c60387a31b25f71e78e968b6e6a98bd4fe092f82#diff-8ef140df8b4408418fab781244480094R1027

Kinda scary :-)

**Comment by stsquad** [comment]
I just ran into this again when updating one of my other machines to native-comp which follow melpa-stable rather than melpa. It's been some time since there was a tagged release - is it time to cut a new one so fixes (including this one) can be available for people who follow stable?

**Comment by jwiegley** [comment]
Yes, good idea, it's time to tag a release.

**Comment by MorganJamesSmith** [comment]
I recently ran into this issue using the Gnu Guix package manager which uses tag 2.4. I would really appreciate a new release :)

**Pull request merged**
