### PR TITLE
Add :hook* keyword

### PR DESCRIPTION
**Pull request by conao3**
This keyword is proposed at #812. Special thanks for @andreyorst.

NOTE:
This PR may not completed. I don't familier with use-package
codebase, I cannot find code that suppress require statemant
when :hook specified.

### CODE REVIEW

**Comment by jwiegley** [comment]
I like this PR, just not so much the name. In other places, `*` means global or "in a different context". Here what you really mean is `:hook-raw` or something that does not do any magic when applying the meaning of the keyword.

**Comment by conao3** [comment]
Same as #828, I couldn't take time on this, honestly.
This code does not have to be committed with my name, so if anyone is interested in doing the rest of the work, I would appreciate it.

**Comment by conao3** [comment]
The license notation may be important. I declare this code as CC0 so that you can freely use it.

**Comment by skangas** [comment]
> The license notation may be important. I declare this code as CC0 so that you can freely use it.

Since you have already assigned copyrights to the FSF for your contributions to Emacs, there is no problem for anyone else to re-use this work for that purpose. So the above is not necessary. That said, the gesture is appreciated.

**Pull request closed without merging**
