### PR TITLE
Fix :after keyword

### PR DESCRIPTION
**Pull request by raxod502**
This should address [this issue](https://github.com/jwiegley/use-package/pull/433#issuecomment-287606553).

### CODE REVIEW

**Comment by drot** [comment]
Can confirm this fixed the issue, thanks.

**Comment by idoo** [comment]
@jwiegley can you please merge it?

**Comment by idoo** [comment]
I've received email from @jwiegley 
```
You've reached me during a weekend when I don't have access to my computer. I'll be able to merge the pull request Sunday night or Monday.
```
so, keep a waiting ;)

**Comment by therockmandolinist** [comment]
@idoo for future reference, consider quoting with `>` char before text instead of monospacing, e.g.:

>You've reached me during a weekend when I don't have access to my computer. I'll be able to merge the pull request Sunday night or Monday.

It's not super important, but improves readability :)

**Comment by seagle0128** [comment]
Please merge it. It works well on my env.

**Comment by raxod502** [comment]
Thanks @jwiegley. Sorry I broke it in the first place :/

**Comment by jwiegley** [comment]
No worries, you just caught me right as I left for a week long vacation without my computer. :)

**Pull request merged**
