### PR TITLE
Add :el-get keyword similar to :ensure

### PR DESCRIPTION
**Pull request by jonEbird**
Use the :el-get keyword to have a package installed via el-get

### CODE REVIEW

**Comment by jonEbird** [comment]
While my patch gets el-get installations working, I'm wondering if you'd prefer to just continue to use `:ensure` with a `:pin el-get` instead?

**Comment by jwiegley** [comment]
I'd much rather that this was placed in its own module, and submitted to `el-get`, rather than having a dependency on el-get within use-package.  There is no way I will ever be able to test this properly.

**Comment by jonEbird** [comment]
That's fine. Could you elaborate on how you might approach putting this into a separate module and submitted to `el-get`? Would it be just updating `use-package-keywords` and defining the necessary functions? Thanks.

**Comment by jwiegley** [comment]
Yes, that should be all that is needed to introduce a new `use-package` keyword from an external package.

**Comment by edvorg** [comment]
Hi. Why do you need explicit :ensure (:el-get) keywords? I mean use package might check for package presence by itself and install it if needed.

**Comment by thomasf** [comment]
@edvorg 
1. specifying package installl names which might differ from their load names
2. selectively overriding built in packages like org-mode
3. not causing additional load/compile times for packages where it's not needed.

**Comment by edvorg** [comment]
Thank you, Thomas.

**Pull request closed without merging**
