### PR TITLE
Add `:magic` and `:magic-fallback` keywords (issue #469).

### PR DESCRIPTION
**Pull request by joewreschnig**
These keywords work equivalently to `:mode` or `:interpreter`, but for
`magic-mode-alist` and `magic-fallback-mode-alist`.

The handler function implementation is now passed a list to add to,
and shared by all four of them.

### CODE REVIEW

**Comment by joewreschnig** [comment]
GitHub doesn't seem to detect issues in the commit title. This is for issue #469.

**Comment by jwiegley** [comment]
This is great, @joewreschnig. Before I merge, have you signed a copyright assignment with the FSF for your work on Emacs?  Since use-package will be merged into Emacs shortly, I need to ensure that all changes have been signed over. If you need help, you can send an e-mail to `assign@gnu.org`.

**Comment by joewreschnig** [comment]
I have not - I'll get on that today. Is [e.g. this org-mode template](http://orgmode.org/request-assign-future.txt) still the right one to start the process? (Replacing org-mode with use-package, of course.)

**Comment by joewreschnig** [comment]
I've sent a request.

**Comment by nickmccurdy** [comment]
@jwiegley It would be great to have a use-package specific template (or you can just tell us how you'd like us to fill out the name) to avoid any legal ambiguity or confusion.

**Comment by joewreschnig** [comment]
The FSF has confirmed and completed the forms.

**Comment by jwiegley** [comment]
Confirmed, thank you!

**Pull request merged**
